/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_gael_openjpeg_OpenJpegDecoder */

#ifndef _Included_fr_gael_openjpeg_OpenJpegDecoder
#define _Included_fr_gael_openjpeg_OpenJpegDecoder
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     fr_gael_openjpeg_OpenJpegDecoder
 * Method:    internalOpenJpegDecodeHeader
 * Signature: ()I
 */
JNIEXPORT jboolean JNICALL Java_fr_gael_openjpeg_OpenJpegDecoder_internalOpenJpegDecodeHeader
  (JNIEnv *, jobject);
    
/*
 * Class:     fr_gael_openjpeg_OpenJpegDecoder
 * Method:    internalOpenJpegDecode
 * Signature: ()I
 */
JNIEXPORT jboolean JNICALL Java_fr_gael_openjpeg_OpenJpegDecoder_internalOpenJpegDecode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
